defaults: &defaults
  main_menu_list_id: 1
  website_title: Integral Rails
  contact_email: change-me@integralrails.com
  # default_preview_image_path: 'previews/default.jpg'
  # google_tag_manager_id: GTM-xxxxx
  # github_url: https://github.com/yamasolutions/integral
  # twitter_url: https://twitter.com/yama_solutions
  # facebook_url: https://www.facebook.com/yamasolutions
  # linkedin_url: https://www.linkedin.com/in/barackobama/
  # youtube_url: https://www.youtube.com/channel/UCUkM9uMpWatT7gVWShgtKFw
  # instagram_url: https://www.instagram.com/jerryoftheday
  # twitter_handler: rails

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
